spring:
  application:
    name: spring-cloud-eureka-server
  security:
    user:
      name: admin
      password: admin
      roles: USER
server:
  port: 8761
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka
    register-with-eureka: false
    fetch-registry: false
management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    health:
      show-details: ALWAYS
