spring:
  application:
    name: spring-cloud-admin-client
eureka:
  instance:
    instance-id: spring-cloud-admin-client
    prefer-ip-address: true
    leaseRenewalIntervalInSeconds: 10
    health-check-url-path: /actuator/health

  client:
    registryFetchIntervalSeconds: 5
    service-url:
      defaultZone: http://admin:admin@127.0.0.1:8761/eureka/
management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    health:
      show-details: ALWAYS
server:
  port: 8762